language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: C2RGwT1WtuaLSIoALNEkMlapESo/pfsPeylffel9lUkiyFT/BlDC9WlPCXzaLD9aJrOWZnWtrF7uBGw/gVa0193ky9EnvgMsWGa5dHwTgPKUAD8PyzWhlNg33KzpNgLeAATAcfcpm5mTRtX7Tw7GE94FRvf4Q1KanDdsTKCGNVJ7wC5J0oZNXmFEqmqZ05wGlRF1jxSHByerr56pJzTS7t3J7XnpfOgMPc4ElDNU37wI4kaGoKZWUNT3avTGYtVQ1ZKiDtnxcouVapm48plcdrxgXd+VYl37WaSjLibwadr7niggNxwCUsv2scQp1etwahQLcdEg82HHlt3eHiv19gnkpeXFr9x+idqAsf8pwdkNKOjJFBXLyFpu4SQaPEJeFn+tEkVVuvgqeYgd/X8LVwh0bha72ZT0V/SmTm1xh6ARGMlVtRldLKEvfwQh/w5YseFRdbld6lEsgKIFkdmnoI/tuV4oBhbv2G2moQasLxRZhgFyzimK5ebKYpJsTZOvKyuNTJ6PlNYwAhsGbV4rDxYurmQaV9XxI+/rkCSIlgmnY9ut83Dogs9nie1v/1PorhqoKnQTPyIxHpT68Dwzc4nY1S8X8jKN5m2DJ+SPlMIiteOzTFKrKOXZcFb6kPqNGMB7k7fqxDLX6budmqAsYOeYTg7jcc6HoAsjOg5emsw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build
after_success:
- test $TRAVIS_BRANCH = "master" && yarn run deploy:travis -- --branch=build
